2024-02-15 19:33:22,890 INFO    MainThread:399010 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-02-15 19:33:22,890 INFO    MainThread:399010 [wandb_setup.py:_flush():76] Configure stats pid to 399010
2024-02-15 19:33:22,890 INFO    MainThread:399010 [wandb_setup.py:_flush():76] Loading settings from /home/akshar/.config/wandb/settings
2024-02-15 19:33:22,890 INFO    MainThread:399010 [wandb_setup.py:_flush():76] Loading settings from /home/akshar/Projects/Fraud_Classification/research/wandb/settings
2024-02-15 19:33:22,890 INFO    MainThread:399010 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-15 19:33:22,890 INFO    MainThread:399010 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:_log_setup():526] Logging user logs to /home/akshar/Projects/Fraud_Classification/research/wandb/run-20240215_193322-2xxifq15/logs/debug.log
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:_log_setup():527] Logging internal logs to /home/akshar/Projects/Fraud_Classification/research/wandb/run-20240215_193322-2xxifq15/logs/debug-internal.log
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f130e349540>
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:init():566] calling init triggers
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'epochs': 10, 'classes': 2, 'batch_size': 16, 'lr': 0.001, 'architecture': 'EfficientNet_B0', 'num_workers': 16}
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:init():616] starting backend
2024-02-15 19:33:22,891 INFO    MainThread:399010 [wandb_init.py:init():620] setting up manager
2024-02-15 19:33:22,893 INFO    MainThread:399010 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-15 19:33:22,893 INFO    MainThread:399010 [wandb_init.py:init():628] backend started and connected
2024-02-15 19:33:22,901 INFO    MainThread:399010 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-02-15 19:33:22,901 INFO    MainThread:399010 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-15 19:33:22,901 INFO    MainThread:399010 [wandb_init.py:init():720] updated telemetry
2024-02-15 19:33:22,901 INFO    MainThread:399010 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-15 19:33:28,774 INFO    MainThread:399010 [wandb_run.py:_on_init():2262] communicating current version
2024-02-15 19:33:29,078 INFO    MainThread:399010 [wandb_run.py:_on_init():2271] got version response 
2024-02-15 19:33:29,079 INFO    MainThread:399010 [wandb_init.py:init():804] starting run threads in backend
2024-02-15 19:33:32,454 INFO    MainThread:399010 [wandb_run.py:_console_start():2241] atexit reg
2024-02-15 19:33:32,454 INFO    MainThread:399010 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-02-15 19:33:32,455 INFO    MainThread:399010 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-02-15 19:33:32,455 INFO    MainThread:399010 [wandb_run.py:_redirect():2186] Redirects installed.
2024-02-15 19:33:32,455 INFO    MainThread:399010 [wandb_init.py:init():847] run started, returning control to user process
2024-02-15 19:33:32,466 INFO    MainThread:399010 [wandb_run.py:_finish():1970] finishing run akshar1895/Insurance_Fraud_detection_CV/2xxifq15
2024-02-15 19:33:32,466 INFO    MainThread:399010 [jupyter.py:save_history():445] not saving jupyter history
2024-02-15 19:33:32,466 INFO    MainThread:399010 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-15 19:33:32,466 INFO    MainThread:399010 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-15 19:33:32,467 INFO    MainThread:399010 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 1
2024-02-15 19:33:32,467 INFO    MainThread:399010 [wandb_run.py:_restore():2193] restore
2024-02-15 19:33:32,467 INFO    MainThread:399010 [wandb_run.py:_restore():2199] restore done
2024-02-15 19:33:38,595 INFO    MainThread:399010 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-02-15 19:33:38,595 INFO    MainThread:399010 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-02-15 19:33:38,598 INFO    MainThread:399010 [wandb_run.py:_footer_sync_info():3825] logging synced files
